title: "Maryllb Blog"
description: "A Jekyll theme based on MDUI"
url: 
baseurl: ""
author: "mignon maryllb"
paginate: 5
paginate_path: "/blog/page:num/"


# Build settings
theme: jekyll-theme-mdui

markdown: kramdown

# highlighter:    rouge
# kramdown:
#   input:                     GFM
#   auto_ids:                  true
#   footnote_nr:               1
#   entity_output:             as_char
#   toc_levels:                1..6
#   smart_quotes:              lsquo,rsquo,ldquo,rdquo
#   enable_coderay:            false
#   hard_wrap:                 true
#   syntax_highlighter:        rouge
#   transliterated_header_ids: true
#   footnote_backlink:         "&#8617;&#xfe0e;"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
